spring:
    application:
        name: X3_Gateway
    config:
        import:
            - optional:file:.env[.properties]
            - classpath:routes.yml
        activate:
            on-profile: default

    security:
        keycloak:
            realm: ${REALM}
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_URI}/realms/${REALM}
            client:
                provider:
                    keycloak:
                        issuer-uri: ${KEYCLOAK_URI}/realms/${REALM}
                        user-name-attribute: preferred_username
                registration:
                    keycloak:
                        client-id: ${CLIENT_ID}
                        client-secret: ${SECRET}
                        scope: openid

#    data:
#        redis:
#            host: ${REDIS_HOST}
#            port: ${REDIS_PORT}
#            password: ${REDIS_PASSWORD}
#    cache:
#        type: redis
#        redis:
#            time-to-live: ${REDIS_TIME}


server:
    port: ${PORT}

logging:
    level:
        org.springframework: INFO
#        org.springframework.security: DEBUG
#        org.springframework.cloud.gateway: TRACE
        com.unknown.gateway: TRACE
    file:
        name: src/main/resources/logging/user-ms.log
    logback:
        rollingpolicy:
            max-file-size: 10MB
            max-history: 10
