routes:
    user:
        - service:
            uri: http://localhost:8080
    post:
        - service:
            uri: http://localhost:8081
    auth:
        - service:
            uri: http://localhost:8079